/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.danielcastellani.gerenciadordetarefas.gui;

import br.danielcastellani.gerenciadordetarefas.controle.TelaTarefaListagemControlador;

/**
 *
 * @author Rafael
 */
public class TelaTarefaListagem extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaTarefaListagem
     */
    TelaTarefaListagemControlador controlador;
    private TelaTarefa telaTarefa;
    
    public TelaTarefaListagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelListagem = new javax.swing.JPanel();

        setClosable(true);
        setTitle("Listagem de Tarefas");
        setPreferredSize(new java.awt.Dimension(800, 426));

        panelListagem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelListagem.setPreferredSize(new java.awt.Dimension(425, 371));

        javax.swing.GroupLayout panelListagemLayout = new javax.swing.GroupLayout(panelListagem);
        panelListagem.setLayout(panelListagemLayout);
        panelListagemLayout.setHorizontalGroup(
            panelListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        panelListagemLayout.setVerticalGroup(
            panelListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 87, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelListagem, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(panelListagem, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelListagem;
    // End of variables declaration//GEN-END:variables


    public javax.swing.JPanel getPanelListagem() {
        return panelListagem;
    }

    /**
     * @param panelListagem the panelListagem to set
     */
    public void setPanelListagem(javax.swing.JPanel panelListagem) {
        this.panelListagem = panelListagem;
    }

    /**
     * @return the telaTarefa
     */
    public TelaTarefa getTelaTarefa() {
        return telaTarefa;
    }

    /**
     * @param telaTarefa the telaProjeto to set
     */
    public void setTelaTarefa(TelaTarefa telaTarefa) {
        this.telaTarefa = telaTarefa;
    }
}
